### ISSUE TITLE
Sign in with google error

### ISSUE THREAD

**Issue by lukasmerta** [PierrickP/multicycles#116]
When trying to sign in with Google, getting an error

Authorization Error
Error 400: redirect_uri_mismatch
The redirect URI in the request, https://flow-api.fluctuo.com/auth/google/callback, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit: https://console.developers.google.com/apis/credentials/oauthclient/996177409050-i79vbi72sbns9lbhou1kge1vgobbp2ee.apps.googleusercontent.com?project=996177409050

**Comment by PierrickP** [comment]
Hello @lukasmerta 
This functionality is deprecated and is not useful for the use of this application.

We will soon clarify the Multicylces situation.
The sole purpose of Multicycles is to serve as a demo for the Data Flow api (see https://flow.fluctuo.com/). 
It is still usable as is but we invite you to try a partner application that uses our api, such as https://escoot.bike/ or https://www.cogoapp.io/.

Best
