### ISSUE TITLE
It doesn't work on iOS 9.3.3

### ISSUE THREAD

**Issue by j0k3r** [PierrickP/multicycles#13]
I'm using an old version of iOS (because of the jailbreak) and the app doesn't load on Safari.
When I check the debug console using my Mac, I got that error:

```
Error: fetch is not found globally and no fetcher passed, to fix pass a fetch for
      your environment like https://www.npmjs.com/package/unfetch.

      For example:
        import fetch from 'unfetch';
        import { createHttpLink } from 'apollo-link-http';

        const link = createHttpLink({ uri: '/graphql', fetch: fetch });
```

It comes from `apollographql/apollo-link`in `httpLink.js`
The `User-Agent` from my device is:
> User-Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_3 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13G34 Safari/601.1

**Comment by PierrickP** [comment]
sorry, i don't have ios and too old version
