### ISSUE TITLE
(required) OpenStreetMap attribution missing on the map

### ISSUE THREAD

**Issue by cquest** [PierrickP/multicycles#14]
Happy to see you're using OpenStreetMap basemap, but less happy to see you're doing so without crediting OSM as required (see http://osm.org/copyright).

Leaflet allows to add credits in the bottom-right corner of the map. As you're using vue.js, I don't know how to fix that and propose a PR.

At https://github.com/PierrickP/multicycles/blob/master/front/src/components/Home.vue#L7 you may have to add something like
`:attribution="&copy; <a href='https://www.openstreetmap.org/copyright'>OpenStreetMap</a> contributors"`

Thanks in advance !

**Comment by PierrickP** [comment]
Hi @cquest You are totaly right.
I ll fix that today.

**Comment by PierrickP** [comment]
I "temporary" moved on Mapbox tiles (with credit). They support retina and have better cdn

**Comment by cquest** [comment]
Thanks for the quick fix !
