### ISSUE TITLE
GeoJSON rather than proprietary JSON layout

### ISSUE THREAD

**Issue by mvl22** [PierrickP/multicycles#25]
The returned JSON seems to be in a specific format rather than GeoJSON, which would enable easier use on Leaflet.js and other mapping providers, which provide native support.

Looking at the output for the live map view, I can't see anything which wouldn't be possible in GeoJSON.

Could GeoJSON be considered as well / instead?

**Comment by PierrickP** [comment]
You should not see it as a simple JSON layout.

The multicycles API is a GraphQL API who aggregate and convert providers API into an unique response.

For API usage, see https://developer.multicycles.org/
