### ISSUE TITLE
PubliBike

### ISSUE THREAD

**Issue by gonzalocasas** [PierrickP/multicycles#28]
https://publibike.ch/

**Comment by gonzalocasas** [comment]
I just tried to clone and work on this myself, but `npm install` fails with a weird error (`src doesn't exist`?):

```
C:\Users\gcasas\alejandria\Repositories\multicycles>npm install

> multicycles@1.0.0-beta.1 prepare C:\Users\gcasas\alejandria\Repositories\multicycles
> npm run clean && npm run transpile


> multicycles@1.0.0-beta.1 clean C:\Users\gcasas\alejandria\Repositories\multicycles
> rm -rf providers/*/lib


> multicycles@1.0.0-beta.1 transpile C:\Users\gcasas\alejandria\Repositories\multicycles
> lerna exec --ignore '@multicycles/{api,front,developer}' -- babel src --optional runtime --out-dir lib --ignore "__tests__"

lerna info version 2.5.1
lerna info versioning independent
lerna info ignore '@multicycles/{api,front,developer}'
Error: Error: Cannot find module 'babel-plugin-transform-runtime' from 'C:\Users\gcasas\alejandria\Repositories\multicycles\front'
    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\cli\lib\babel\dir.js:143:22
    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\cli\lib\babel\dir.js:106:23
    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\cli\lib\babel\dir.js:78:23
    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\cli\lib\babel\dir.js:40:23
    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\cli\lib\babel\util.js:76:16
    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\transform-file.js:39:14
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:667:11)
    at startup (bootstrap_node.js:187:16)
lerna ERR! exec Errored while executing 'babel src --optional runtime --out-dir lib --ignore __tests__' in '@multicycles/front'
lerna ERR! execute callback with error
lerna ERR! Error: spawn babel ENOENT
lerna ERR!     at notFoundError (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\cross-spawn\lib\enoent.js:11:11)
lerna ERR!     at verifyENOENT (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\cross-spawn\lib\enoent.js:46:16)
lerna ERR!     at ChildProcess.cp.emit (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\cross-spawn\lib\enoent.js:33:19)
src doesn't exist
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
lerna ERR! exec Errored while executing 'babel src --optional runtime --out-dir lib --ignore __tests__' in '@multicycles/developer'
🎉  Successfully compiled 1 file with Babel.
🎉  Successfully compiled 1 file with Babel.
(node:25940) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 7): Error: spawn babel ENOENT
(node:25940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multicycles@1.0.0-beta.1 transpile: `lerna exec --ignore '@multicycles/{api,front,developer}' -- babel src --optional runtime --out-dir lib --ignore "__tests__"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multicycles@1.0.0-beta.1 transpile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gcasas\AppData\Roaming\npm-cache\_logs\2018-06-25T14_18_47_541Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multicycles@1.0.0-beta.1 prepare: `npm run clean && npm run transpile`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the multicycles@1.0.0-beta.1 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gcasas\AppData\Roaming\npm-cache\_logs\2018-06-25T14_18_47_710Z-debug.log
```

**Comment by PierrickP** [comment]
You can try `npm run watch`, it's should create `providers/**/src`

For publibike, currently i'm not focus on bikes with dock, but it's not rejected.
We just need to find the right format for station (probably a new field or a type like `CLUSTER_BIKE`)

**Comment by gonzalocasas** [comment]
@PierrickP thanks! Running `npm run watch` doesn't totally fail (i.e. doesn't exit), but it does not seem to work either. There's the same `no src` error in the middle and after the compiling, it's not clear it if triggered anything, but there's nothing listening on 3000.

<details>
<summary>npm run watch</summary>
<pre>
C:\Users\gcasas\alejandria\Repositories\multicycles>npm run watch

> multicycles@1.0.0-beta.1 watch C:\Users\gcasas\alejandria\Repositories\multicycles
> lerna exec --ignore '@multicycles/{api,front,developer}' --parallel -- babel -w src --optional runtime --out-dir lib --ignore "__tests__"

lerna info version 2.5.1
lerna info versioning independent
lerna info ignore '@multicycles/{api,front,developer}'
lerna info exec in 18 package(s): babel -w src --optional runtime --out-dir lib --ignore __tests__
@multicycles/api: src doesn't exist
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: babel -w src --optional runtime --out-dir lib --ignore __tests__
lerna ERR! src doesn't exist
lerna ERR!
lerna ERR!lerna ERR!     at Promise.all.then.arr (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
lerna WARN complete Waiting for 17 child processes to exit. CTRL-C to exit immediately.
@multicycles/developer: src doesn't exist
@multicycles/front: { Error: Cannot find module 'babel-preset-stage-2' from 'C:\Users\gcasas\alejandria\Repositories\multicycles\front'\n    at Function.module.exports [as sync] (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\resolve\lib\sync.js:40:15)\n    at resolveStandardizedName (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:78:29)\n    at resolvePreset (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:31:10)\n    at loadPreset (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:50:18)\n    at createDescriptor (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:152:21)\n    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:104:12\n    at
Array.map (<anonymous>)\n    at createDescriptors (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:103:27)\n    at createPresetDescriptors (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:95:10)\n    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:67:19 code: 'MODULE_NOT_FOUND' }
@multicycles/front: { Error: Cannot find module 'babel-preset-stage-2' from 'C:\Users\gcasas\alejandria\Repositories\multicycles\front'\n    at Function.module.exports [as sync] (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\resolve\lib\sync.js:40:15)\n    at resolveStandardizedName (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:78:29)\n    at resolvePreset (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:31:10)\n    at loadPreset (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:50:18)\n    at createDescriptor (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:152:21)\n    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:104:12\n    at
Array.map (<anonymous>)\n    at createDescriptors (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:103:27)\n    at createPresetDescriptors (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:95:10)\n    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:67:19 code: 'MODULE_NOT_FOUND' }
@multicycles/front: { Error: Cannot find module 'babel-preset-stage-2' from 'C:\Users\gcasas\alejandria\Repositories\multicycles\front'\n    at Function.module.exports [as sync] (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\resolve\lib\sync.js:40:15)\n    at resolveStandardizedName (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:78:29)\n    at resolvePreset (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:31:10)\n    at loadPreset (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:50:18)\n    at createDescriptor (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:152:21)\n    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:104:12\n    at
Array.map (<anonymous>)\n    at createDescriptors (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:103:27)\n    at createPresetDescriptors (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:95:10)\n    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:67:19 code: 'MODULE_NOT_FOUND' }
@multicycles/front: { Error: Cannot find module 'babel-preset-stage-2' from 'C:\Users\gcasas\alejandria\Repositories\multicycles\front'\n    at Function.module.exports [as sync] (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\resolve\lib\sync.js:40:15)\n    at resolveStandardizedName (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:78:29)\n    at resolvePreset (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:31:10)\n    at loadPreset (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:50:18)\n    at createDescriptor (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:152:21)\n    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:104:12\n    at
Array.map (<anonymous>)\n    at createDescriptors (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:103:27)\n    at createPresetDescriptors (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:95:10)\n    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:67:19 code: 'MODULE_NOT_FOUND' }
@multicycles/front: 🎉  Successfully compiled 0 file with Babel.
@multicycles/front: { Error: Cannot find module 'babel-preset-stage-2' from 'C:\Users\gcasas\alejandria\Repositories\multicycles\front'\n    at Function.module.exports [as sync] (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\resolve\lib\sync.js:40:15)\n    at resolveStandardizedName (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:78:29)\n    at resolvePreset (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:31:10)\n    at loadPreset (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\files\plugins.js:50:18)\n    at createDescriptor (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:152:21)\n    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:104:12\n    at
Array.map (<anonymous>)\n    at createDescriptors (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:103:27)\n    at createPresetDescriptors (C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:95:10)\n    at C:\Users\gcasas\alejandria\Repositories\multicycles\node_modules\@babel\core\lib\config\config-descriptors.js:67:19 code: 'MODULE_NOT_FOUND' }
@multicycles/donkey: 🎉  Successfully compiled 1 file with Babel.
@multicycles/mobike: 🎉  Successfully compiled 1 file with Babel.
@multicycles/publibike: 🎉  Successfully compiled 1 file with Babel.
@multicycles/byke: 🎉  Successfully compiled 1 file with Babel.
@multicycles/jump: 🎉  Successfully compiled 2 files with Babel.
@multicycles/bird: 🎉  Successfully compiled 1 file with Babel.
@multicycles/spin: 🎉  Successfully compiled 1 file with Babel.
@multicycles/gobee.bike: 🎉  Successfully compiled 1 file with Babel.
@multicycles/indigowheel: 🎉  Successfully compiled 1 file with Babel.
@multicycles/lime: 🎉  Successfully compiled 1 file with Babel.
@multicycles/pony: 🎉  Successfully compiled 1 file with Babel.
@multicycles/ofo: 🎉  Successfully compiled 1 file with Babel.
@multicycles/yobike: 🎉  Successfully compiled 1 file with Babel.
@multicycles/obike: 🎉  Successfully compiled 1 file with Babel.
@multicycles/whitebikes: 🎉  Successfully compiled 1 file with Babel.
</pre>
</details

**Comment by PierrickP** [comment]
i just git clone & `npm i` and it's worked :\ :\
Did you use a recent node ?
Check if modules are correctly setup with `npm ls`

**Comment by gonzalocasas** [comment]
node is `v8.6.0`

There are several modules on `ERR`. I tried manually installing some of them but didn't work. I guess it's Windows crapware not working for this. I will try on mac later tonight. 

<details>
   <summary>npm ls</summary>
<pre>
npm ERR! missing: mkdirp@0.5.1, required by node-pre-gyp@0.10.0
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: minimatch@3.0.4, required by ignore-walk@3.0.1
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: console-control-strings@1.1.0, required by npmlog@4.1.2
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.1, required by string_decoder@1.1.1
npm ERR! missing: console-control-strings@1.1.0, required by gauge@2.7.4
npm ERR! missing: string-width@1.0.2, required by gauge@2.7.4
npm ERR! missing: strip-ansi@3.0.1, required by gauge@2.7.4
npm ERR! missing: code-point-at@1.1.0, required by string-width@1.0.2
npm ERR! missing: is-fullwidth-code-point@1.0.0, required by string-width@1.0.2
npm ERR! missing: strip-ansi@3.0.1, required by string-width@1.0.2
npm ERR! missing: number-is-nan@1.0.1, required by is-fullwidth-code-point@1.0.0
npm ERR! missing: ansi-regex@2.1.1, required by strip-ansi@3.0.1
npm ERR! missing: string-width@1.0.2, required by wide-align@1.1.2
npm ERR! missing: inherits@2.0.3, required by glob@7.1.2
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by glob@7.1.2
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: minipass@2.2.4, required by tar@4.4.1
npm ERR! missing: mkdirp@0.5.1, required by tar@4.4.1
npm ERR! missing: safe-buffer@5.1.1, required by tar@4.4.1
npm ERR! missing: yallist@3.0.2, required by tar@4.4.1
npm ERR! missing: minipass@2.2.4, required by fs-minipass@1.2.5
npm ERR! missing: safe-buffer@5.1.1, required by minipass@2.2.4
npm ERR! missing: yallist@3.0.2, required by minipass@2.2.4
npm ERR! missing: minipass@2.2.4, required by minizlib@1.1.0
</pre>
</details>

**Comment by gonzalocasas** [comment]
alright, `npm install` works on linux, so it's really a Windows issue. Is `npm run watch` supposed to launch the server process or should I start those individually?

**Comment by PierrickP** [comment]
oh yeah you probably need VS redistibutate, some module need to compile.
You need to start each (npm start or npm run dev 😄 )

**Comment by PierrickP** [comment]
I updated README.md, follow https://github.com/PierrickP/multicycles#contribute
