### ISSUE TITLE
Txfy

### ISSUE THREAD

**Issue by PierrickP** [PierrickP/multicycles#38]
http://www.leparisien.fr/info-paris-ile-de-france-oise/transports/paris-bientot-de-nouvelles-trottinettes-electriques-en-libre-service-18-07-2018-7825272.php

**Comment by jzarca01** [comment]
Txfy s'est rebrandé en Bolt -> https://github.com/jzarca01/node-bolt

**Comment by PierrickP** [comment]
81aa083fbbd4b4b87634f7b0a690440bc77fef71
