### ISSUE TITLE
Suggestion : le temps d'inactivité d'un vélo

### ISSUE THREAD

**Issue by djakk** [PierrickP/multicycles#4]
Salut, je découvre ton super projet via le twitter de EmmanuelSPV ! 👍 
Une suggestion : montrer les vélos qui sont restés inactifs pendant longtemps par rapport à la moyenne constatée dans le secteur, car ce sont ceux qui sont vandalisés ou privatisés !

**Comment by PierrickP** [comment]
Hello, 
Merci pour ta suggestion. Pour l'instant je ne stock pas les positions pour statistiques / autres, donc pas faisable a cours terme.
L'info servirait a qui ? l'utilisateur ou la compagnie ?
Je suis tombé une autre personnes qui en faisait, je vais essayer de le contacter.

**Comment by PierrickP** [comment]
ah! mais c’était toi ! 😹 
Comment tu as récupéré l'endpoint de gobee ?

**Comment by PierrickP** [comment]
Out of scope of this projet.
I'm working on another projet for data on Paris
