### ISSUE TITLE
No nextbikes in Augsburg, Bayern, Germany

### ISSUE THREAD

**Issue by graphcon** [PierrickP/multicycles#51]
Hi Pierrick,

when I jump to Augsburg on your Website (multicycles.org) I don't see any Nextbikes around (they are called SWA Rad there but Nextbike's app shows them).

Yours
Raul

**Comment by PierrickP** [comment]
here ? https://multicycles.org/?l=48.365918979699956,10.886850357055664
Only 31 stations :) it's a small town

**Comment by graphcon** [comment]
All right, yesterday it didn't work. Now it does. Thanks

**Comment by graphcon** [comment]
Now it doesn't work again :(
![image](https://user-images.githubusercontent.com/3214585/48077659-17a2af00-e1e8-11e8-9388-3f0fc447ceb3.png)
