### ISSUE TITLE
Cityscoot

### ISSUE THREAD

**Issue by nightwolf93** [PierrickP/multicycles#68]
Bonjour,

J'ai déjà essayer de vous contacter par Linkedin, aucune réponse.
Vous utilisez les API Cityscoot sans consentement de notre part.

Pouvez-vous me fournir une adresse sur laquelle vous contactez en privé pour régler ce problème.

**Comment by PierrickP** [comment]
Bonjour,
Je n'ai trouvé aucun message de votre part dans ma messagerie linkedin.
Vous pouvez me contacter sur contact@multicycles.org

Cordialement,

**Comment by nightwolf93** [comment]
C'est fait.
