### ISSUE TITLE
Create a tel-o-fun provider

### ISSUE THREAD

**Issue by balderman1** [PierrickP/multicycles#69]
tel-o-fun is a bike rental service located in Tel Aviv Israel. See https://www.tel-o-fun.co.il/en/
I would like to implement a new provider for this service.
The service has no public API and the data will be fetched using scraping.
Does multicycles have another scraping based provider so I can look at it?
How the data is normalized? I did not see this code in the providers code.

Avishay

**Comment by balderman1** [comment]
I have asked tel-o-fun to get their API but got no response.
Therefore I came with this clumsy scraping  node js implementation below.

See https://pastebin.com/e7cSJGbu

**Comment by PierrickP** [comment]
@balderman1 it's now available ;)
