### ISSUE TITLE
jump scooters api

### ISSUE THREAD

**Issue by Arjun-sna** [PierrickP/multicycles#74]
the API https://dc.jumpmobility.com/opendata for JUMP is only for bikes. Is there a separate API for jump scooters?

**Comment by PierrickP** [comment]
Hello Arjun,

Indeed, there are a different API for Jump Scooter.
Multicycles API use https://dc.jumpmobility.com/opendata and other endpoints.
All Jump scooters / bikes are available through our API for each cities where they are.

Best
