### ISSUE TITLE
Lime not showing up in Göteborg/Gothenburg(Sweden)

### ISSUE THREAD

**Issue by vmellgre** [PierrickP/multicycles#75]
Seems to work in Stockholm(Sweden)

**Comment by PierrickP** [comment]
@vmellgre Hello,
Thank you ! It should be good now.
For some cities, we need to manually activate it.
We ll check other main Sweden cities

**Comment by vmellgre** [comment]
Works fine now. Quick response! Nice service in general, first time I tried it, will spread the word :)
