### ISSUE TITLE
Issue with Scoot result

### ISSUE THREAD

**Issue by Arjun-sna** [PierrickP/multicycles#77]
Scoot results are returned in individual provider queries but not shown in vehicle queries for any location.

**Comment by Arjun-sna** [comment]
Also, Bird and Spin bike do not show anywhere in results. Also, checked in multicycles.org and that too doesn't show the result for those providers.

**Comment by PierrickP** [comment]
I activated Scoot in SF

For Bird/Spin, it could have some temporary unvalibility.
Without precis location, we can't check

**Comment by Arjun-sna** [comment]
@PierrickP Here is coords which actually returns Spin and Lime with gbfs url. but multicycles API do not return Spin and Lime. Can you please check.

```
{
  "lat": 38.8931,
  "lng": -77.0175
}
```
